import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:go_router/go_router.dart';
import '../../../../core/constants/app_colors.dart';import '../../../../core/constants/app_sizes.dart';import '../../../../core/constants/app_spacing.dart';import '../../../../core/constants/app_text_styles.dart';import '../../../../core/widgets/authentication_prompt.dart';import '../../../../l10n/app_localizations.dart';import '../../../auth/presentation/providers/auth_provider.dart';import '../../../customer/complaints/domain/entities/complaint_entities.dart';import 'providers/provider_complaint_providers.dart';
class ProviderComplaintScreen extends ConsumerWidget{final String requestId,providerId;const ProviderComplaintScreen({super.key,required this.requestId,required this.providerId});@override Widget build(BuildContext context,WidgetRef ref){final l=AppLocalizations.of(context)!;final auth=ref.watch(authStateProvider);if(auth.isLoading)return const _Loading();if(auth.valueOrNull?.role.toLowerCase()!='provider')return AuthenticationPrompt(message:l.providerOnlyMessage);if(requestId.isEmpty||providerId.isEmpty)return _Error(message:l.complaintUnavailable);final state=ref.watch(providerComplaintProvider((requestId:requestId,providerId:providerId)));return Scaffold(backgroundColor:AppColors.scaffoldBackground,appBar:AppBar(title:Text(l.complaintDetails),leading:IconButton(onPressed:()=>context.pop(),tooltip:l.back,icon:const Icon(Icons.arrow_back_rounded))),body:state.when(loading:()=>const _Loading(),error:(_,__)=>_Error(message:l.complaintUnavailable),data:(c)=>c==null?_Error(message:l.complaintUnavailable):_Details(complaint:c)));}}
class _Details extends StatelessWidget{final Complaint complaint;const _Details({required this.complaint});@override Widget build(BuildContext context){final l=AppLocalizations.of(context)!;final status=complaint.status==ComplaintStatus.submitted?l.complaintSubmittedStatus:complaint.status==ComplaintStatus.underReview?l.complaintUnderReview:complaint.status==ComplaintStatus.resolved?l.complaintResolved:l.complaintRejected;return SingleChildScrollView(padding:const EdgeInsets.all(AppSpacing.xxl),child:Column(crossAxisAlignment:CrossAxisAlignment.stretch,children:[Container(padding:const EdgeInsets.all(AppSpacing.xl),decoration:BoxDecoration(gradient:const LinearGradient(colors:[AppColors.secondary,AppColors.secondaryLight]),borderRadius:BorderRadius.circular(AppSizes.radiusXl)),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(l.complaintReference(complaint.complaintId),style:AppTextStyles.heading3.copyWith(color:AppColors.white)),const SizedBox(height:AppSpacing.sm),Text(l.requestReference(complaint.requestId),style:AppTextStyles.bodySmall.copyWith(color:AppColors.white70)),const SizedBox(height:AppSpacing.lg),_Status(status:status)])),const SizedBox(height:AppSpacing.xxl),_Card(title:l.complaintCategory,value:_category(l,complaint.categoryId)),_Card(title:l.complaintDescription,value:complaint.description),_Card(title:l.evidencePhotos,value:complaint.attachments.isEmpty?l.noReviews:l.complaintAttachmentCount(complaint.attachments.length)),if(complaint.attachments.isNotEmpty)Wrap(spacing:AppSpacing.sm,runSpacing:AppSpacing.sm,children:complaint.attachments.map((a)=>ClipRRect(borderRadius:BorderRadius.circular(AppSizes.radiusMd),child:a.bytes==null?Container(width:88,height:88,color:AppColors.surface,child:const Icon(Icons.image_rounded,color:AppColors.primary)):Image.memory(a.bytes!,width:88,height:88,fit:BoxFit.cover))).toList()),_Card(title:l.complaintStatus,value:status)]));}
String _category(AppLocalizations l,String key){switch(key){case 'serviceQuality':return l.serviceQuality;case 'providerBehavior':return l.providerBehavior;case 'pricingIssue':return l.pricingIssue;case 'incompleteService':return l.incompleteService;case 'damageOrLoss':return l.damageOrLoss;default:return l.otherComplaint;}}
}
class _Status extends StatelessWidget{final String status;const _Status({required this.status});@override Widget build(BuildContext context)=>Container(padding:const EdgeInsets.symmetric(horizontal:AppSpacing.md,vertical:AppSpacing.sm),decoration:BoxDecoration(color:AppColors.primary.withOpacity(.16),borderRadius:BorderRadius.circular(AppSizes.radiusPill)),child:Text(status,style:AppTextStyles.label.copyWith(color:AppColors.white)));}
class _Card extends StatelessWidget{final String title,value;const _Card({required this.title,required this.value});@override Widget build(BuildContext context)=>Container(margin:const EdgeInsets.only(bottom:AppSpacing.md),padding:const EdgeInsets.all(AppSpacing.lg),decoration:BoxDecoration(color:AppColors.card,borderRadius:BorderRadius.circular(AppSizes.radiusLg),border:Border.all(color:AppColors.border)),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(title,style:AppTextStyles.label.copyWith(color:AppColors.primaryDark)),const SizedBox(height:AppSpacing.sm),Text(value,style:AppTextStyles.bodySmall)]));}
class _Loading extends StatelessWidget{const _Loading();@override Widget build(BuildContext context)=>const Scaffold(body:Center(child:CircularProgressIndicator(color:AppColors.primary)));}class _Error extends StatelessWidget{final String message;const _Error({required this.message});@override Widget build(BuildContext context)=>Scaffold(body:Center(child:Text(message,textAlign:TextAlign.center)));}
